### ISSUE TITLE
Question related to MvcElmahDashboard project 

### ISSUE THREAD

**Issue by mmuekk** [codetuner/Arebis.Pdf#1]
Hello Rudi, 
Today I found out about your MvcElmahDashboard project,  when I was searching for a elmah dashboard. 
I would like to make some changes,  so I searched it on github, but I didn't found it. 
After Google it,  I found out that you are MvcElmahDashboard creator
I would like to know,  if you could add it to github, so I could fork it, or add pull requests to it. 
Sorry for contacting you this way, but I couldn't find your email or Twitter 

Best regards 
@mmuekk

**Comment by codetuner** [comment]
Hello,
Of course I'll be glad to provide the Elmahdashboard source in Github. I'm doing myself the move to Github and had not yet migrated the Elmah Dashboard, but I've now done it and you can find it on:
https://github.com/codetuner/Arebis.Web.Mvc.ElmahDashboard

Kind regards
